// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSu_JwzP8RZQiwo6KuvJn8wzbjWlpSQ4w',
    appId: '1:752102080047:web:ceb79bbf48b0069dd4d0da',
    messagingSenderId: '752102080047',
    projectId: 'weatherai-ed1c5',
    authDomain: 'weatherai-ed1c5.firebaseapp.com',
    storageBucket: 'weatherai-ed1c5.firebasestorage.app',
    measurementId: 'G-WZTET3ML81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVwHTKO2_jf7MBLDhFHDwJnnMcsPf3JuI',
    appId: '1:752102080047:android:c2d60db17112e9bbd4d0da',
    messagingSenderId: '752102080047',
    projectId: 'weatherai-ed1c5',
    storageBucket: 'weatherai-ed1c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU3ZPkkkHVj1ut0Gz2ZZRwMPGBEZwwNqo',
    appId: '1:752102080047:ios:06014775a6aef714d4d0da',
    messagingSenderId: '752102080047',
    projectId: 'weatherai-ed1c5',
    storageBucket: 'weatherai-ed1c5.firebasestorage.app',
    iosBundleId: 'com.example.weatherai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU3ZPkkkHVj1ut0Gz2ZZRwMPGBEZwwNqo',
    appId: '1:752102080047:ios:06014775a6aef714d4d0da',
    messagingSenderId: '752102080047',
    projectId: 'weatherai-ed1c5',
    storageBucket: 'weatherai-ed1c5.firebasestorage.app',
    iosBundleId: 'com.example.weatherai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSu_JwzP8RZQiwo6KuvJn8wzbjWlpSQ4w',
    appId: '1:752102080047:web:4864f3442ae0e79cd4d0da',
    messagingSenderId: '752102080047',
    projectId: 'weatherai-ed1c5',
    authDomain: 'weatherai-ed1c5.firebaseapp.com',
    storageBucket: 'weatherai-ed1c5.firebasestorage.app',
    measurementId: 'G-CY6G4T94PH',
  );
}
